#!/bin/sh
#
# Start/stop nullmailer
#

DAEMON="/usr/sbin/nullmailer-send"
PID_FILE="/run/nullmailer.pid"
LOG_FILE="/var/log/nullmailer.log"
DAEMON_USER=nullmail:nullmail

case "$1" in
	start)
		printf "Starting nullmailer: "
		touch ${LOG_FILE}
		chown ${DAEMON_USER} ${LOG_FILE}
		cd /var/spool/nullmailer
		start-stop-daemon -S -q -c ${DAEMON_USER} -m -p ${PID_FILE} -b \
			-a /bin/sh -- -c "exec ${DAEMON} >>${LOG_FILE} 2>&1"
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping nullmailer: "
		start-stop-daemon -K -x "${DAEMON}" -p "${PID_FILE}" -o
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart)
		"$0" stop
		sleep 1
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
